# Generated by Django 4.1.5 on 2023-01-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0005_auto_20230127_2142"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
